* Seoul

Seoul is x86 Virtual Machine Monitor including device modules and
instruction emulator. It is a standalone version of the Vancouver VMM
that is included in [[https://github.com/TUD-OS/NUL][NUL]] developed mainly by Bernhard Kauer
(bk@vmmon.org) at the TU Dresden. Please direct questions regarding
Seoul to Julian Stecklina <jsteckli@os.inf.tu-dresden.de>.

This repository contains a frontend for Seoul runnable on Linux,
FreeBSD and perhaps other UNIX-likes implemented in =unix/=. This
frontend is currently work-in-progress and not intended for anything
except further development.

The goal is to keep this UNIX frontend only a showcase for how to get
Seoul running on your platform. All other parts of Seoul do not invoke
platform-specific functions on their own and should be reusable on
most platforms without change.

This repository also contains drivers developed for NUL in =host=.

* Building the UNIX demo

The Unix frontend builds with gcc 4.7 on Linux. To build it you need
scons and a complete 32-bit development environment.  If you are ready
to give it a go, execute =scons= in =unix/= to start the build
process. Help regarding build options can be obtained via =scons -h=.

We currently only support booting Multiboot compliant kernels. Execute
=seoul -h= to get usage information.

Serial output is redirected to standard output. VGA is available to
the VM, but currently not displayed to the user.
